version: "3.8"

services:
  token-images-cdn:
    build:
      context: .
    ports:
      - 127.0.0.1:${PORT:-4100}:4100
    volumes:
      - token-images-cdn:/var/lib/token-images-cdn
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  token-images-cdn:
