version: "3.8"

services:
  token-images-cdn:
    build:
      context: .
    container_name: token-images-cdn
    ports:
      - ${PORT:-4100}:4100
    volumes:
      - token-images-cdn:/var/lib/token-images-cdn
    restart: on-failure
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-4100}
      - GRAPHQL_API=${GRAPHQL_API:-https://api-graphql.raygraph.io}
      - GREST_API=${GREST_API:-https://api.koios.rest/api/v0}
      - IPFS_API=${IPFS_API:-https://cloudflare-ipfs.com}
      - CDN_FOLDER=${CDN_FOLDER:-/var/lib/token-images-cdn}
      - IMG_SIZES=${IMG_SIZES:-["32", "64", "128", "256", "512", "1024"]}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  token-images-cdn:
